---
unpack:
  - source: /run/archiso/bootmnt/abora/x86_64/airootfs.sfs
    sourcefs: squashfs
    destination: ""
  - source: /run/archiso/bootmnt/arch/x86_64/airootfs.sfs
    sourcefs: squashfs
    destination: ""
    optional: true
