#!/usr/bin/env python3
"""Abora Feedback — graphical front-end for Abora's existing support tools."""

from __future__ import annotations

import os
import shutil
import subprocess
import tempfile
import threading
from pathlib import Path

import gi

gi.require_version("Gtk", "4.0")
gi.require_version("Adw", "1")
from gi.repository import Adw, GLib, Gtk


ISSUE_REPO = os.environ.get("ABORA_ISSUE_REPO", "AnimatedGTVR/Abora-OS")
LOG_LINES = 200


def run_command(command: list[str], timeout: int = 60) -> tuple[int, str, str]:
    try:
        result = subprocess.run(
            command,
            capture_output=True,
            text=True,
            timeout=timeout,
            env=os.environ.copy(),
        )
        return result.returncode, result.stdout, result.stderr
    except FileNotFoundError:
        return 127, "", f"Command not found: {command[0]}"
    except subprocess.TimeoutExpired:
        return 124, "", f"Command timed out after {timeout} seconds"
    except Exception as exc:
        return 1, "", str(exc)


def collect_logs() -> str:
    rc, stdout, stderr = run_command(["abora", "logs", "--lines", str(LOG_LINES)], timeout=15)
    if rc == 0:
        return stdout.strip()
    return (stderr or stdout or "No logs were available.").strip()


def create_support_report() -> tuple[str | None, str | None]:
    output_dir = Path.home() / "Desktop"
    if not output_dir.exists():
        output_dir = Path.home()
    rc, stdout, stderr = run_command(
        ["abora", "support-report", "--output-dir", str(output_dir)], timeout=120
    )
    if rc != 0:
        return None, (stderr or stdout or "Support report creation failed.").strip()

    # The CLI prints the generated archive path. Prefer a path that actually
    # exists, but keep the final non-empty line as a fallback for older builds.
    lines = [line.strip() for line in stdout.splitlines() if line.strip()]
    for line in reversed(lines):
        candidate = Path(line).expanduser()
        if candidate.exists():
            return str(candidate), None
    return (lines[-1] if lines else None), None


def issue_body(summary: str, details: str, logs: str, support_archive: str | None) -> str:
    body = [
        "## Summary",
        "",
        summary.strip() or "No summary provided.",
        "",
        "## What happened?",
        "",
        details.strip() or "No additional details provided.",
        "",
        "## Diagnostics",
        "",
    ]

    if support_archive:
        body += [
            f"- Support archive created locally: `{support_archive}`",
            "- Review the archive before attaching it publicly.",
            "",
        ]
    else:
        body += ["- Support archive: not collected", ""]

    if logs:
        # GitHub issue bodies are finite; 200 log lines can still be large, so
        # cap the preview/body while preserving the newest output from `abora logs`.
        trimmed = logs[-12000:]
        body += ["### Recent Abora logs", "", "```text", trimmed, "```", ""]
    else:
        body += ["- Recent logs: not included", ""]

    body += [
        "---",
        "Generated by Abora Feedback GUI.",
    ]
    return "\n".join(body)


class FeedbackWindow(Adw.ApplicationWindow):
    __gtype_name__ = "AboraFeedbackWindow"

    def __init__(self, app: Adw.Application):
        super().__init__(
            application=app,
            title="Abora Feedback",
            default_width=620,
            default_height=720,
        )
        Adw.StyleManager.get_default().set_color_scheme(Adw.ColorScheme.DEFAULT)
        self._logs = ""
        self._support_archive: str | None = None
        self._busy = False
        self._build_ui()

    def _build_ui(self):
        toolbar = Adw.ToolbarView()
        self.set_content(toolbar)
        toolbar.add_top_bar(Adw.HeaderBar())

        scroller = Gtk.ScrolledWindow(vexpand=True)
        clamp = Adw.Clamp(maximum_size=580)
        scroller.set_child(clamp)
        toolbar.set_content(scroller)

        content = Gtk.Box(
            orientation=Gtk.Orientation.VERTICAL,
            spacing=18,
            margin_top=24,
            margin_bottom=24,
            margin_start=12,
            margin_end=12,
        )
        clamp.set_child(content)

        heading = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=6)
        title = Gtk.Label(label="Tell us what went wrong", xalign=0)
        title.add_css_class("title-1")
        subtitle = Gtk.Label(
            label="Describe the issue, choose what diagnostic information to include, then preview it before opening GitHub.",
            xalign=0,
            wrap=True,
        )
        subtitle.add_css_class("dim-label")
        heading.append(title)
        heading.append(subtitle)
        content.append(heading)

        report_group = Adw.PreferencesGroup(title="Report")
        content.append(report_group)

        self.summary_entry = Adw.EntryRow(title="Short summary")
        report_group.add(self.summary_entry)

        details_row = Adw.ActionRow(title="What happened?")
        self.details = Gtk.TextView(wrap_mode=Gtk.WrapMode.WORD_CHAR)
        self.details.set_top_margin(8)
        self.details.set_bottom_margin(8)
        self.details.set_left_margin(8)
        self.details.set_right_margin(8)
        details_frame = Gtk.Frame()
        details_frame.set_child(self.details)
        details_row.set_child(details_frame)
        report_group.add(details_row)

        diag_group = Adw.PreferencesGroup(
            title="Diagnostics",
            description="Nothing is uploaded automatically. You can preview everything first.",
        )
        content.append(diag_group)

        self.logs_switch = Gtk.Switch(active=True, valign=Gtk.Align.CENTER)
        logs_row = Adw.ActionRow(
            title=f"Include recent logs",
            subtitle=f"Runs: abora logs --lines {LOG_LINES}",
        )
        logs_row.add_suffix(self.logs_switch)
        logs_row.set_activatable_widget(self.logs_switch)
        diag_group.add(logs_row)

        self.support_switch = Gtk.Switch(active=True, valign=Gtk.Align.CENTER)
        support_row = Adw.ActionRow(
            title="Create support report",
            subtitle="Runs: abora support-report and saves the archive locally",
        )
        support_row.add_suffix(self.support_switch)
        support_row.set_activatable_widget(self.support_switch)
        diag_group.add(support_row)

        self.status_row = Adw.ActionRow(
            title="Ready",
            subtitle="Your report has not been collected or sent.",
        )
        diag_group.add(self.status_row)

        actions = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=8, halign=Gtk.Align.END)
        self.collect_btn = Gtk.Button(label="Collect & Preview")
        self.collect_btn.connect("clicked", self._collect)
        self.submit_btn = Gtk.Button(label="Open GitHub Issue")
        self.submit_btn.add_css_class("suggested-action")
        self.submit_btn.set_sensitive(False)
        self.submit_btn.connect("clicked", self._open_github)
        actions.append(self.collect_btn)
        actions.append(self.submit_btn)
        content.append(actions)

        preview_group = Adw.PreferencesGroup(title="Preview")
        content.append(preview_group)
        self.preview = Gtk.TextView(
            editable=False,
            cursor_visible=False,
            monospace=True,
            wrap_mode=Gtk.WrapMode.WORD_CHAR,
        )
        self.preview.set_top_margin(10)
        self.preview.set_bottom_margin(10)
        self.preview.set_left_margin(10)
        self.preview.set_right_margin(10)
        preview_scroll = Gtk.ScrolledWindow(min_content_height=220, vexpand=True)
        preview_scroll.set_child(self.preview)
        preview_frame = Gtk.Frame()
        preview_frame.set_child(preview_scroll)
        preview_group.add(preview_frame)

    def _text(self, view: Gtk.TextView) -> str:
        buffer = view.get_buffer()
        start, end = buffer.get_bounds()
        return buffer.get_text(start, end, True)

    def _set_busy(self, busy: bool, message: str):
        self._busy = busy
        self.collect_btn.set_sensitive(not busy)
        self.submit_btn.set_sensitive(not busy and bool(self._text(self.preview).strip()))
        self.status_row.set_title(message)

    def _collect(self, *_args):
        if self._busy:
            return
        self._set_busy(True, "Collecting diagnostics…")
        threading.Thread(target=self._collect_worker, daemon=True).start()

    def _collect_worker(self):
        logs = collect_logs() if self.logs_switch.get_active() else ""
        support_archive = None
        support_error = None
        if self.support_switch.get_active():
            support_archive, support_error = create_support_report()
        GLib.idle_add(self._collection_done, logs, support_archive, support_error)

    def _collection_done(self, logs: str, support_archive: str | None, support_error: str | None):
        self._logs = logs
        self._support_archive = support_archive
        body = issue_body(
            self.summary_entry.get_text(),
            self._text(self.details),
            logs,
            support_archive,
        )
        self.preview.get_buffer().set_text(body)
        if support_error:
            self.status_row.set_subtitle(f"Support report failed: {support_error}")
        elif support_archive:
            self.status_row.set_subtitle(f"Support archive: {support_archive}")
        else:
            self.status_row.set_subtitle("Preview generated. Nothing has been uploaded.")
        self._set_busy(False, "Preview ready")
        self.submit_btn.set_sensitive(True)
        return False

    def _open_github(self, *_args):
        body = self._text(self.preview).strip()
        if not body:
            return

        title = self.summary_entry.get_text().strip() or "Abora OS bug report"
        fd, body_path = tempfile.mkstemp(prefix="abora-feedback-", suffix=".md")
        os.close(fd)
        Path(body_path).write_text(body)

        gh = shutil.which("gh")
        if gh:
            command = [
                gh,
                "issue",
                "create",
                "--repo",
                ISSUE_REPO,
                "--title",
                title,
                "--body-file",
                body_path,
                "--web",
            ]
            try:
                subprocess.Popen(command)
                self.status_row.set_title("GitHub issue opened")
                self.status_row.set_subtitle(
                    "Review the issue in your browser. Attach the support archive manually if you chose to create one."
                )
                return
            except Exception:
                pass

        # Fall back to the existing Abora CLI, which already handles the case
        # where gh is unavailable or unauthenticated and prints the issue URL.
        try:
            subprocess.Popen(
                [
                    "abora",
                    "bug-report",
                    "--github",
                    "--title",
                    title,
                    "--body-file",
                    body_path,
                    "--web",
                ]
            )
            self.status_row.set_title("Opening existing Abora bug-report flow")
            self.status_row.set_subtitle("The GUI report body was passed to abora bug-report.")
        except Exception as exc:
            self.status_row.set_title("Could not open GitHub")
            self.status_row.set_subtitle(str(exc))


class FeedbackApp(Adw.Application):
    def __init__(self):
        super().__init__(application_id="org.abora.Feedback")

    def do_activate(self):
        window = self.props.active_window
        if window is None:
            window = FeedbackWindow(self)
        window.present()


if __name__ == "__main__":
    app = FeedbackApp()
    raise SystemExit(app.run(None))
