background #07101d
foreground #dce9ff
selection_background #15304f
selection_foreground #dce9ff
cursor #8fc8ff
cursor_text_color #07101d

active_tab_background #5aa9ff
active_tab_foreground #07101d
inactive_tab_background #122235
inactive_tab_foreground #91a7bf

color0  #07101d
color1  #f7768e
color2  #9ece6a
color3  #e0af68
color4  #5aa9ff
color5  #bb9af7
color6  #7dcfff
color7  #dce9ff
color8  #213248
color9  #ff899d
color10 #b9f27c
color11 #f3c784
color12 #8fc8ff
color13 #ccb0ff
color14 #95e6ff
color15 #f3f8ff

font_size 11.5
confirm_os_window_close 0
shell_integration enabled
